exclude = [
    "Packages/*",
    "src/ReplicatedStorage/Framework/*",
    "src/ServerScriptService/Server/Network/*",
    "src/ReplicatedStorage/TowerGame/Network/*",
    "src/StarterPlayerScripts/PlayerModule/*",
    "src/StarterPlayerScripts/Client/Game/ScriptRepo/*"
]
std = "selene-std"

[rules]
global_usage = "allow"
