std = "roblox"
exclude = [
    "src/ReplicatedStorage/Packages/*",
    "src/ReplicatedStorage/Framework/*",
    "src/StarterPlayerScripts/PlayerModule/*",
    "src/StarterPlayerScripts/MultiTowerClient/ScriptRepo/*"
]
[rules]
global_usage = "allow"
incorrect_standard_library_use = "allow"