[package]
name = "zylx/multi-tower-kit"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
lyra = "paradoxum-games/lyra@0.6.0"
topbarplus = "1foreverhd/topbarplus@3.4.0"
conch = "alicesaidhi/conch@0.3.1"
conch-ui = "alicesaidhi/conch-ui@0.3.1"
satchel = "ryanlua/satchel@1.4.1"
janitor = "howmanysmall/janitor@^1.18.3"
promise = "evaera/promise@4.0.0"
reflex = "littensy/reflex@4.3.1"
charm = "littensy/charm@0.10.0"
signal = "sleitnick/signal@2.0.3"
sift = "csqrl/sift@0.0.11"
t = "osyrisrblx/t@3.1.1"