--[[
	Anti-cheat kick messages. Use {Player} for player name.
]]

local KICK_MESSAGES: { string } = {
	"{Player} wasn't an epic gamer",
	"{Player} wasn't a cool kid",
	"{Player} did an oopsie",
	"{Player} was yeeted from the server",
	"{Player} tried their best but didn't succeed",
	"{Player}'s gaming chair was just too good",
	"{Player} loves this game so much that they cheated",
}

return KICK_MESSAGES
