[dependencies]
conch = "alicesaidhi/conch@0.3.1"
language = "alicesaidhi/conch-language@0.3.1"
vide = "centau/vide@^0.3.1"

[package]
exclude = [
    "pesde.toml",
    "pesde.lock",
    "src",
    "roblox_packages",
    "luau_packages",
    "**/stories",
]
include = ["/dist"]
name = "alicesaidhi/conch-ui"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.3.1"
