--[[

Zylx EToH Fangame Kit
* originally made by fanofpixels and rewrite by zylx
Version 4.0

-------------------------------------------

All MTK scripts and default UI were created by fanofpixels/Ethan Pixelate.
Example Tower 1 & Example Tower 2 built by fanopfixels/Ethan Pixelate.

-------------------------------------------

Credit goes to the JToH team for scripts taken from the JToH Tower Creation Kit v5.4.

-------------------------------------------

]]
--
